theme: jekyll-theme-slate

# Name of website
title: Tropicalia, matière à débat

# Short description of your site
description: Arguments pour et contre la plus grande serre tropicale au monde sur la Côte d’Opale (Pas de Calais)

image: https://live.staticflickr.com/2048/31960907074_8aa06b7e62_b.jpg

locale: fr_FR
