theme: jekyll-theme-slate

# Name of website
title: Tropicalia, matière à débat

# Short description of your site
description: Arguments pour et contre la plus grande serre tropicale au monde sur la Côte d’Opale (Pas de Calais)

defaults:
  - scope:
      path: ""
    values:
      image: https://france3-regions.francetvinfo.fr/hauts-de-france/sites/regions_france3/files/styles/top_big/public/assets/images/2020/01/05/octavtirziu.com_caau_tropicalia_web2-4587569.jpg
